// Generated code. Do not modify.

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};
#[allow(unused_imports)]
use crate::types::*;


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]#[serde(tag = "type")]pub enum Entity {    #[serde(rename = "entity_with_array")]    EntityWithArray(EntityWithArray),    #[serde(rename = "entity_with_array_of_enums")]    EntityWithArrayOfEnums(EntityWithArrayOfEnums),    #[serde(rename = "entity_with_array_of_expressions")]    EntityWithArrayOfExpressions(EntityWithArrayOfExpressions),    #[serde(rename = "entity_with_array_of_nested_items")]    EntityWithArrayOfNestedItems(EntityWithArrayOfNestedItems),    #[serde(rename = "entity_with_array_with_transform")]    EntityWithArrayWithTransform(EntityWithArrayWithTransform),    #[serde(rename = "entity_with_complex_property")]    EntityWithComplexProperty(EntityWithComplexProperty),    #[serde(rename = "entity_with_complex_property_with_default_value")]    EntityWithComplexPropertyWithDefaultValue(EntityWithComplexPropertyWithDefaultValue),    #[serde(rename = "entity_with_entity_property")]    EntityWithEntityProperty(EntityWithEntityProperty),    #[serde(rename = "entity_with_optional_complex_property")]    EntityWithOptionalComplexProperty(EntityWithOptionalComplexProperty),    #[serde(rename = "entity_with_optional_property")]    EntityWithOptionalProperty(EntityWithOptionalProperty),    #[serde(rename = "entity_with_optional_string_enum_property")]    EntityWithOptionalStringEnumProperty(EntityWithOptionalStringEnumProperty),    #[serde(rename = "entity_with_property_with_default_value")]    EntityWithPropertyWithDefaultValue(EntityWithPropertyWithDefaultValue),    #[serde(rename = "entity_with_raw_array")]    EntityWithRawArray(EntityWithRawArray),    #[serde(rename = "entity_with_required_property")]    EntityWithRequiredProperty(EntityWithRequiredProperty),    #[serde(rename = "entity_with_simple_properties")]    EntityWithSimpleProperties(EntityWithSimpleProperties),    #[serde(rename = "entity_with_string_array_property")]    EntityWithStringArrayProperty(EntityWithStringArrayProperty),    #[serde(rename = "entity_with_string_enum_property")]    EntityWithStringEnumProperty(EntityWithStringEnumProperty),    #[serde(rename = "entity_with_string_enum_property_with_default_value")]    EntityWithStringEnumPropertyWithDefaultValue(EntityWithStringEnumPropertyWithDefaultValue),    #[serde(rename = "entity_without_properties")]    EntityWithoutProperties(EntityWithoutProperties),}
